**NUMPY**

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

Array : Collection of similiar datatypes
List : Collection of different datatypes

In [3]:
lst=list(range(1,25))
print(lst)
arr=np.array(lst)
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [4]:
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [5]:
#array : function in numpy to create an array
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
print(type(arr))
arr

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
lst=list(range(1,25))
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [7]:
#arange() : used tp create the array with specified range
arr=np.arange(1,25)
arr #single dimensional array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [8]:
#2D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr) 

[[1 2 3]
 [4 5 6]]


In [9]:
# Create an array with all elements values 0
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#3D array : 2 blocks, 2 rows, 3 columns
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
arr=np.array([[[1,2,3],[3,2,1]]]) #x axis value is 1
arr

array([[[1, 2, 3],
        [3, 2, 1]]])

In [12]:
# Create an array with all elements values 1
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#Create an array with specified range and equal distance
arr=np.linspace(1,10,5) # (start,end,num of elements)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
# Create 2d array with linspace function
arr=np.linspace(1,10,5).reshape(5,1) #row will be 5 and column 1
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [15]:
# Creating 1D to 2D with reshape()
arr=np.arange(0,30).reshape(10,3) # (rows,columns)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [16]:
# Tells the dimensions of the array
arr.shape

(10, 3)

In [17]:
# Creating 2D to 3D array using reshape()
arr=np.arange(0,30).reshape(3,5,2) # (blocks,rows,columns)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [18]:
#Random Initialization : Generates random values within specified range
arr=np.random.randint(1,5,9) #(start,end,num of elements)
arr

array([2, 4, 1, 1, 3, 1, 3, 4, 2])

In [19]:
arr=np.random.randint(1,5,9).reshape(3,3)
arr

array([[1, 3, 2],
       [1, 4, 3],
       [2, 3, 3]])

In [20]:
arr=np.random.randint(1,5,(3,3)) #Here we have defined the rows and columns
arr

array([[4, 4, 1],
       [2, 1, 3],
       [3, 1, 2]])

In [21]:
arr=np.random.randint(1,5,(3,3,3)) #for 3D array add the third dimension 
arr

array([[[4, 1, 4],
        [2, 3, 4],
        [3, 2, 1]],

       [[1, 3, 4],
        [2, 2, 4],
        [3, 3, 3]],

       [[2, 4, 4],
        [1, 2, 4],
        [2, 2, 3]]])

In [22]:
# Random(n) generates n values between 0 to 1 
arr=np.random.random(10)
arr

array([0.7234709 , 0.65281254, 0.72429921, 0.22587788, 0.95467457,
       0.40171336, 0.28221715, 0.40505227, 0.89521299, 0.51241737])

In [23]:
#Randint(n) generates a singal values between 0 to n randomlly
arr= np.random.randint(10)
arr

1

In [24]:
arr=np.random.random((3,4))
arr

array([[0.03706255, 0.53939457, 0.01111009, 0.82784145],
       [0.56605933, 0.99867523, 0.24423249, 0.16248551],
       [0.10342351, 0.93954611, 0.47827688, 0.90675019]])

In [25]:
print(arr.dtype) # Data type
print(arr.ndim) # dimension
print(arr.size) # size of array(no. of elements)
print(arr.shape) # rows and columns

float64
2
12
(3, 4)


In [26]:
arr.flatten() # Converts 3D or 2D to 1D array

array([0.03706255, 0.53939457, 0.01111009, 0.82784145, 0.56605933,
       0.99867523, 0.24423249, 0.16248551, 0.10342351, 0.93954611,
       0.47827688, 0.90675019])

In [27]:
arr.ravel() # Converts 3D or 2D to 1D array

array([0.03706255, 0.53939457, 0.01111009, 0.82784145, 0.56605933,
       0.99867523, 0.24423249, 0.16248551, 0.10342351, 0.93954611,
       0.47827688, 0.90675019])

In [28]:
lst=[1,2,3,4]
arr=np.array(lst)
print(arr)

[1 2 3 4]


In [29]:
arr.shape

(4,)

In [30]:
arr.T.shape # used to transpose an array

(4,)

In [31]:
arr=np.array([[1,2,3],[1,2,3]])
print(arr)
print(arr.shape)
print(arr.T.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)
(3, 2)


In [32]:
arr.T

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
#Slicing
arr=np.array([1,10,1,3,5,6,7,8,9,12,15])
arr[3:11]

array([ 3,  5,  6,  7,  8,  9, 12, 15])

In [38]:
lst=list(range(1,100))
arr=np.array(lst)
arr[6:90]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90])

In [39]:
arr[0:22:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [42]:
arr.reshape(33,3)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
arr=np.arange(0,30).reshape(10,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
arr[0:5,1:2] #0:5 is row ; 1:2 is column(counts 1st index not the 2nd one)

array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13]])

In [47]:
arr[6,1]

19

In [48]:
arr[-1][-1]

29

In [49]:
arr[:4][-1]

array([ 9, 10, 11])

In [51]:
arr[3,1]=134

In [58]:
arr=np.arange(0,30).reshape(3,5,2)

In [59]:
arr[0][2:]

array([[4, 5],
       [6, 7],
       [8, 9]])

In [60]:
arr[0][2:5]

array([[4, 5],
       [6, 7],
       [8, 9]])

In [61]:
arr[:,0:1,0:1]

array([[[ 0]],

       [[10]],

       [[20]]])

In [63]:
arr[2][3][1]=500
arr

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]],

       [[ 10,  11],
        [ 12,  13],
        [ 14,  15],
        [ 16,  17],
        [ 18,  19]],

       [[ 20,  21],
        [ 22,  23],
        [ 24,  25],
        [ 26, 500],
        [ 28,  29]]])

In [64]:
np.arange(60)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [65]:
arr -1

array([[[ -1,   0],
        [  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8]],

       [[  9,  10],
        [ 11,  12],
        [ 13,  14],
        [ 15,  16],
        [ 17,  18]],

       [[ 19,  20],
        [ 21,  22],
        [ 23,  24],
        [ 25, 499],
        [ 27,  28]]])

In [66]:
arr

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]],

       [[ 10,  11],
        [ 12,  13],
        [ 14,  15],
        [ 16,  17],
        [ 18,  19]],

       [[ 20,  21],
        [ 22,  23],
        [ 24,  25],
        [ 26, 500],
        [ 28,  29]]])

In [77]:
x=list(range(1,10))
y=list(range(21,30))
print(x+y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [78]:
arr1=np.array(x)
arr2=np.array(y)
arr1+arr2

array([22, 24, 26, 28, 30, 32, 34, 36, 38])

In [ ]:
arr1*arr2 #can mutliply two array but can't multiply two lists

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261])